// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdhebrxkhcewzehfbcar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkaGVicnhraGNld3plaGZiY2FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MDAyODMsImV4cCI6MjA3MjQ3NjI4M30._5hzo7Zkf4vE67MPHlvyVVHrB2eIZ6ZRBx0-_krpa8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});